name: chat_room
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: yamazorn <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  built_collection: 4.0.0
  built_value: ^6.1.6
  shelf: ^0.7.3
  shelf_proxy: ^0.1.0
  shelf_web_socket: ^0.2.2
  web_socket_channel: ^1.0.0
dev_dependencies:
  test: ^1.5.1
  build_runner: ^1.1.1
  build_web_compilers: ^0.4.4