name: poc
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: yamazorn <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
#  path: ^1.4.1
  json_annotation: ^2.0.0


dev_dependencies:
  test: ^1.0.0
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
