name: course
<<<<<<< HEAD
description: my dart course learning
environment:
  sdk: '>=2.0.0 < 3.0.0'

dev_dependencies:
  test: ^1.0.0
=======
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: yamazorn <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
>>>>>>> 4c57532127c4407386633ffab9e202fe9e1eb8dd
